"""user model updates.

Revision ID: 94a22a3a9e71
Revises: cb85e66995d2
Create Date: 2025-04-02 11:49:55.996670

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "94a22a3a9e71"
down_revision = "cb85e66995d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "frai_assessment",
        "responsive_parenting",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.alter_column(
        "frai_assessment",
        "family_engagement",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.alter_column(
        "frai_assessment",
        "socio_economic",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.alter_column(
        "frai_assessment",
        "overall_score",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.add_column(
        "user_model", sa.Column("username", sa.String(length=200), nullable=True),
    )
    op.create_unique_constraint(None, "user_model", ["username"])
    op.drop_column("user_model", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_model",
        sa.Column(
            "password", sa.VARCHAR(length=200), autoincrement=False, nullable=False,
        ),
    )
    op.drop_constraint(None, "user_model", type_="unique")
    op.drop_column("user_model", "username")
    op.alter_column(
        "frai_assessment",
        "overall_score",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    op.alter_column(
        "frai_assessment",
        "socio_economic",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    op.alter_column(
        "frai_assessment",
        "family_engagement",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    op.alter_column(
        "frai_assessment",
        "responsive_parenting",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    # ### end Alembic commands ###
