"""add_sso_fields.

Revision ID: 5e345a9af4ce
Revises: add_sso_fields
Create Date: 2025-04-02 14:25:33.317376

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5e345a9af4ce"
down_revision = "add_sso_fields"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_external_id", "user_model", type_="unique")
    op.drop_column("user_model", "external_id")
    op.drop_column("user_model", "identity_provider")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_model",
        sa.Column(
            "identity_provider", sa.VARCHAR(), autoincrement=False, nullable=True,
        ),
    )
    op.add_column(
        "user_model",
        sa.Column("external_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint("uq_user_external_id", "user_model", ["external_id"])
    # ### end Alembic commands ###
