"""Adding init family table.

Revision ID: ac979d128de4
Revises: fc3b388f6b3d
Create Date: 2025-03-17 03:04:39.878040

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ac979d128de4"
down_revision = "fc3b388f6b3d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initial_family_model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("family_name", sa.String(length=200), nullable=False),
        sa.Column("child_dob", sa.Date(), nullable=False),
        sa.Column("nhs_number", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("initial_family_model")
    # ### end Alembic commands ###
