"""Updated frat assessmentt id pkey.

Revision ID: 008a775434ac
Revises: 665567ed1e78
Create Date: 2025-03-23 17:11:45.434132

"""



# revision identifiers, used by Alembic.
revision = "008a775434ac"
down_revision = "665567ed1e78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
