"""Added family info table details.

Revision ID: 16c031d7dc97
Revises: e1505eec964e
Create Date: 2025-03-17 11:25:01.336610

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16c031d7dc97"
down_revision = "e1505eec964e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("main_parent_first_name", sa.String(length=200), nullable=False),
        sa.Column("main_parent_last_name", sa.String(length=200), nullable=False),
        sa.Column("main_parent_dob", sa.String(length=200), nullable=False),
        sa.Column("main_parent_gender", sa.String(length=100), nullable=False),
        sa.Column(
            "main_parent_relation_to_child",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column("main_parent_education_level", sa.String(length=200), nullable=False),
        sa.Column("main_parent_parental_responsibility", sa.Boolean(), nullable=False),
        sa.Column("main_parent_information_provider", sa.Boolean(), nullable=False),
        sa.Column("support_parent_first_name", sa.String(length=200), nullable=False),
        sa.Column("support_parent_last_name", sa.String(length=200), nullable=False),
        sa.Column("support_parent_dob", sa.String(length=200), nullable=False),
        sa.Column("support_parent_gender", sa.String(length=100), nullable=False),
        sa.Column(
            "support_parent_relation_to_child",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "support_parent_education_level",
            sa.String(length=200),
            nullable=False,
        ),
        sa.Column(
            "support_parent_parental_responsibility",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column("support_parent_information_provider", sa.Boolean(), nullable=False),
        sa.Column("child_first_name", sa.String(length=200), nullable=False),
        sa.Column("child_last_name", sa.String(length=200), nullable=False),
        sa.Column("child_gender", sa.String(length=100), nullable=False),
        sa.Column("child_dob", sa.String(length=200), nullable=False),
        sa.Column("child_support_parent", sa.Boolean(), nullable=False),
        sa.Column(
            "child_support_parent_first_name",
            sa.String(length=200),
            nullable=False,
        ),
        sa.Column(
            "child_support_parent_last_name",
            sa.String(length=200),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["initial_families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("family_details")
    # ### end Alembic commands ###
