"""Updated frat assessment composite key.

Revision ID: 665567ed1e78
Revises: b90a53e46223
Create Date: 2025-03-23 16:10:32.786476

"""



# revision identifiers, used by Alembic.
revision = "665567ed1e78"
down_revision = "b90a53e46223"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
