"""Add composite primary key to frat_assessment table.

Revision ID: 84ae1c2a2c25
Revises: 008a775444ac
Create Date: 2025-03-23 17:17:08.474391

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "84ae1c2a2c25"
down_revision = "84ae1c2a1b16"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create a temporary table with the new schema
    op.execute(text("""
        CREATE TABLE frai_assessment_new (
            id INTEGER NOT NULL,
            assessmentid VARCHAR(200) NOT NULL,
            responsive_parenting VARCHAR(200),
            family_health VARCHAR(200) NOT NULL,
            family_engagement VARCHAR(200),
            family_support VARCHAR(200) NOT NULL,
            socio_economic VARCHAR(200),
            overall_score VARCHAR(200),
            PRIMARY KEY (id, assessmentid),
            FOREIGN KEY (id) REFERENCES initial_families(id)
        )
    """))

    # Step 2: Copy all data from the old table to the new table
    op.execute(text("""
        INSERT INTO frai_assessment_new
        SELECT * FROM frai_assessment
    """))

    # Step 3: Drop the old table
    op.execute(text("DROP TABLE frai_assessment"))

    # Step 4: Rename the new table to the original name
    op.execute(text("ALTER TABLE frai_assessment_new RENAME TO frai_assessment"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("""
        CREATE TABLE frai_assessment_old (
            id INTEGER NOT NULL PRIMARY KEY,
            responsive_parenting VARCHAR(200),
            family_health VARCHAR(200) NOT NULL,
            family_engagement VARCHAR(200),
            family_support VARCHAR(200) NOT NULL,
            socio_economic VARCHAR(200),
            overall_score VARCHAR(200)
            FOREIGN KEY (id) REFERENCES initial_families(id)
        )
    """))

    # Copy the data - only keeping one record per id
    # This potentially loses data if there are multiple assessments per ID
    op.execute(text("""
        INSERT INTO frai_assessment_old
        SELECT DISTINCT ON (id) *
        FROM frai_assessment
    """))

    # Drop the current table
    op.execute(text("DROP TABLE frai_assessment"))

    # Rename the old schema table to the original name
    op.execute(text("ALTER TABLE frat_assessmeni_old RENAME TO frai_assessment"))
    # ### end Alembic commands ###
