"""Change family table details.

Revision ID: e1505eec964e
Revises: 2c5a87e68d3f
Create Date: 2025-03-17 09:31:55.370100

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1505eec964e"
down_revision = "2c5a87e68d3f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "initial_families",
        "child_dob",
        existing_type=sa.DATE(),
        type_=sa.String(length=200),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "initial_families",
        "child_dob",
        existing_type=sa.String(length=200),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
