"""Added new column on frat assessment table details.

Revision ID: 6787e9cad374
Revises: 412350343e8e
Create Date: 2025-03-20 12:19:34.411160

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6787e9cad374"
down_revision = "412350343e8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "frat_assessment",
        sa.Column("assessmentid", sa.String(length=200), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("frat_assessment", "assessmentid")
    # ### end Alembic commands ###
