"""Added frat assessment table details.

Revision ID: f05039035a53
Revises: 16c031d7dc97
Create Date: 2025-03-17 22:07:05.110627

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f05039035a53"
down_revision = "16c031d7dc97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "frat_assessment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assessment_1", sa.String(length=200), nullable=False),
        sa.Column("assessment_2", sa.String(length=200), nullable=False),
        sa.Column("assessment_3", sa.String(length=200), nullable=False),
        sa.Column("assessment_4", sa.String(length=200), nullable=False),
        sa.Column("assessment_5", sa.String(length=200), nullable=False),
        sa.Column("assessment_6", sa.String(length=200), nullable=False),
        sa.Column("assessment_7", sa.String(length=200), nullable=False),
        sa.Column("assessment_8", sa.String(length=200), nullable=False),
        sa.Column("assessment_9", sa.String(length=200), nullable=False),
        sa.Column("assessment_10", sa.String(length=200), nullable=False),
        sa.Column("assessment_11", sa.String(length=200), nullable=False),
        sa.Column("assessment_12", sa.String(length=200), nullable=False),
        sa.Column("assessment_13", sa.String(length=200), nullable=False),
        sa.Column("assessment_14", sa.String(length=200), nullable=False),
        sa.Column("assessment_15", sa.String(length=200), nullable=False),
        sa.Column("assessment_16", sa.String(length=200), nullable=False),
        sa.Column("assessment_17", sa.String(length=200), nullable=False),
        sa.Column("assessment_18", sa.String(length=200), nullable=False),
        sa.Column("assessment_19", sa.String(length=200), nullable=False),
        sa.Column("assessment_20", sa.String(length=200), nullable=False),
        sa.Column("assessment_21", sa.String(length=200), nullable=False),
        sa.Column("assessment_22", sa.String(length=200), nullable=False),
        sa.Column("assessment_23", sa.String(length=200), nullable=False),
        sa.Column("assessment_24", sa.String(length=200), nullable=False),
        sa.Column("assessment_25", sa.String(length=200), nullable=False),
        sa.Column("assessment_26", sa.String(length=200), nullable=False),
        sa.Column("assessment_27", sa.String(length=200), nullable=False),
        sa.Column("assessment_28", sa.String(length=200), nullable=False),
        sa.Column("assessment_29", sa.String(length=200), nullable=False),
        sa.Column("assessment_30", sa.String(length=200), nullable=False),
        sa.Column("assessment_31", sa.String(length=200), nullable=False),
        sa.Column("assessment_32", sa.String(length=200), nullable=False),
        sa.Column("assessment_33", sa.String(length=200), nullable=False),
        sa.Column("assessment_34", sa.String(length=200), nullable=False),
        sa.Column("assessment_35", sa.String(length=200), nullable=False),
        sa.Column("assessment_36", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["initial_families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("frat_assessment")
    # ### end Alembic commands ###
