"""Add composite primary key to frat_assessment table.

Revision ID: 84ae1c2a1b16
Revises: 008a775444ac
Create Date: 2025-03-23 17:17:08.474391

"""
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "84ae1c2a1b16"
down_revision = "008a775444ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create a temporary table with the new schema
    op.execute(text("""
        CREATE TABLE frat_assessment_new (
            id INTEGER NOT NULL,
            assessmentid VARCHAR(200) NOT NULL,
            assessment_1 VARCHAR(200),
            assessment_2 VARCHAR(200) NOT NULL,
            assessment_3 VARCHAR(200),
            assessment_4 VARCHAR(200) NOT NULL,
            assessment_5 VARCHAR(200),
            assessment_6 VARCHAR(200),
            assessment_7 VARCHAR(200),
            assessment_8 VARCHAR(200),
            assessment_9 VARCHAR(200),
            assessment_10 VARCHAR(200),
            assessment_11 VARCHAR(200),
            assessment_12 VARCHAR(200),
            assessment_13 VARCHAR(200),
            assessment_14 VARCHAR(200),
            assessment_15 VARCHAR(200),
            assessment_16 VARCHAR(200) NOT NULL,
            assessment_17 VARCHAR(200),
            assessment_18 VARCHAR(200) NOT NULL,
            assessment_19 VARCHAR(200),
            assessment_20 VARCHAR(200),
            assessment_21 VARCHAR(200) NOT NULL,
            assessment_22 VARCHAR(200),
            assessment_23 VARCHAR(200),
            assessment_24 VARCHAR(200),
            assessment_25 VARCHAR(200),
            assessment_26 VARCHAR(200),
            assessment_27 VARCHAR(200),
            assessment_28 VARCHAR(200),
            assessment_29 VARCHAR(200),
            assessment_30 VARCHAR(200),
            assessment_31 VARCHAR(200),
            assessment_32 VARCHAR(200),
            assessment_33 VARCHAR(200),
            assessment_34 VARCHAR(200),
            assessment_35 VARCHAR(200),
            assessment_36 VARCHAR(200),
            PRIMARY KEY (id, assessmentid),
            FOREIGN KEY (id) REFERENCES initial_families(id)
        )
    """))

    # Step 2: Copy all data from the old table to the new table
    op.execute(text("""
        INSERT INTO frat_assessment_new
        SELECT * FROM frat_assessment
    """))

    # Step 3: Drop the old table
    op.execute(text("DROP TABLE frat_assessment"))

    # Step 4: Rename the new table to the original name
    op.execute(text("ALTER TABLE frat_assessment_new RENAME TO frat_assessment"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("""
        CREATE TABLE frat_assessment_old (
            id INTEGER NOT NULL PRIMARY KEY,
            assessmentid VARCHAR(200) NOT NULL,
            assessment_1 VARCHAR(200),
            assessment_2 VARCHAR(200) NOT NULL,
            assessment_3 VARCHAR(200),
            assessment_4 VARCHAR(200) NOT NULL,
            assessment_5 VARCHAR(200),
            assessment_6 VARCHAR(200),
            assessment_7 VARCHAR(200),
            assessment_8 VARCHAR(200),
            assessment_9 VARCHAR(200),
            assessment_10 VARCHAR(200),
            assessment_11 VARCHAR(200),
            assessment_12 VARCHAR(200),
            assessment_13 VARCHAR(200),
            assessment_14 VARCHAR(200),
            assessment_15 VARCHAR(200),
            assessment_16 VARCHAR(200) NOT NULL,
            assessment_17 VARCHAR(200),
            assessment_18 VARCHAR(200) NOT NULL,
            assessment_19 VARCHAR(200),
            assessment_20 VARCHAR(200),
            assessment_21 VARCHAR(200) NOT NULL,
            assessment_22 VARCHAR(200),
            assessment_23 VARCHAR(200),
            assessment_24 VARCHAR(200),
            assessment_25 VARCHAR(200),
            assessment_26 VARCHAR(200),
            assessment_27 VARCHAR(200),
            assessment_28 VARCHAR(200),
            assessment_29 VARCHAR(200),
            assessment_30 VARCHAR(200),
            assessment_31 VARCHAR(200),
            assessment_32 VARCHAR(200),
            assessment_33 VARCHAR(200),
            assessment_34 VARCHAR(200),
            assessment_35 VARCHAR(200),
            assessment_36 VARCHAR(200),
            FOREIGN KEY (id) REFERENCES initial_families(id)
        )
    """))

    # Copy the data - only keeping one record per id
    # This potentially loses data if there are multiple assessments per ID
    op.execute(text("""
        INSERT INTO frat_assessment_old
        SELECT DISTINCT ON (id) *
        FROM frat_assessment
    """))

    # Drop the current table
    op.execute(text("DROP TABLE frat_assessment"))

    # Rename the old schema table to the original name
    op.execute(text("ALTER TABLE frat_assessment_old RENAME TO frat_assessment"))
    # ### end Alembic commands ###
