"""Add composite primary key to frat_assessment table

Revision ID: 008a775444ac
Revises: 665567ed1e78
Create Date: 2025-03-23 17:11:45.434132

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "008a775444ac"
down_revision = "008a775434ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Drop the primary key constraint
    op.drop_constraint('frat_assessment_pkey', 'frat_assessment', type_='primary')

    # Step 2: Add a new composite primary key
    op.create_primary_key('frat_assessment_pkey', 'frat_assessment', ['id', 'assessmentid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert back to the original schema
    op.drop_constraint('frat_assessment_pkey', 'frat_assessment', type_='primary')
    op.create_primary_key('frat_assessment_pkey', 'frat_assessment', ['id'])
    # ### end Alembic commands ###
