"""Updated family table details.

Revision ID: b90a53e46223
Revises: 6787e9cad374
Create Date: 2025-03-21 23:26:15.636285

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b90a53e46223"
down_revision = "6787e9cad374"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "children",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=200), nullable=False),
        sa.Column("last_name", sa.String(length=200), nullable=False),
        sa.Column("gender", sa.String(length=100), nullable=False),
        sa.Column("dob", sa.String(length=200), nullable=False),
        sa.Column("support_parent", sa.Boolean(), nullable=False),
        sa.Column("support_parent_first_name", sa.String(length=200), nullable=False),
        sa.Column("support_parent_last_name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family_details.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "supporting_parents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=200), nullable=False),
        sa.Column("last_name", sa.String(length=200), nullable=False),
        sa.Column("dob", sa.String(length=200), nullable=False),
        sa.Column("gender", sa.String(length=100), nullable=False),
        sa.Column("relation_to_child", sa.String(length=100), nullable=False),
        sa.Column("education_level", sa.String(length=200), nullable=False),
        sa.Column("parental_responsibility", sa.Boolean(), nullable=False),
        sa.Column("information_provider", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"], ["family_details.id"], ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("family_details", "support_parent_relation_to_child")
    op.drop_column("family_details", "support_parent_dob")
    op.drop_column("family_details", "child_support_parent_last_name")
    op.drop_column("family_details", "support_parent_last_name")
    op.drop_column("family_details", "child_support_parent_first_name")
    op.drop_column("family_details", "support_parent_parental_responsibility")
    op.drop_column("family_details", "support_parent_first_name")
    op.drop_column("family_details", "child_gender")
    op.drop_column("family_details", "support_parent_education_level")
    op.drop_column("family_details", "child_first_name")
    op.drop_column("family_details", "child_support_parent")
    op.drop_column("family_details", "child_dob")
    op.drop_column("family_details", "support_parent_gender")
    op.drop_column("family_details", "child_last_name")
    op.drop_column("family_details", "support_parent_information_provider")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "family_details",
        sa.Column(
            "support_parent_information_provider",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "child_last_name",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "support_parent_gender",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "child_dob", sa.VARCHAR(length=200), autoincrement=False, nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "child_support_parent", sa.BOOLEAN(), autoincrement=False, nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "child_first_name",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "support_parent_education_level",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "child_gender", sa.VARCHAR(length=100), autoincrement=False, nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "support_parent_first_name",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "support_parent_parental_responsibility",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "child_support_parent_first_name",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "support_parent_last_name",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "child_support_parent_last_name",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "support_parent_dob",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "family_details",
        sa.Column(
            "support_parent_relation_to_child",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("supporting_parents")
    op.drop_table("children")
    # ### end Alembic commands ###
