"""Added frai assessment table details.

Revision ID: 724803c49356
Revises: f05039035a53
Create Date: 2025-03-18 07:38:06.413108

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "724803c49356"
down_revision = "f05039035a53"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "frai_assessment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("responsive_parenting", sa.String(length=200), nullable=False),
        sa.Column("family_health", sa.String(length=200), nullable=False),
        sa.Column("family_engagement", sa.String(length=200), nullable=False),
        sa.Column("family_support", sa.String(length=200), nullable=False),
        sa.Column("socio_economic", sa.String(length=200), nullable=False),
        sa.Column("overall_score", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["initial_families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("frai_assessment")
    # ### end Alembic commands ###
