"""Change family table name.

Revision ID: 2c5a87e68d3f
Revises: ac979d128de4
Create Date: 2025-03-17 03:12:28.346086

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c5a87e68d3f"
down_revision = "ac979d128de4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initial_families",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("family_name", sa.String(length=200), nullable=False),
        sa.Column("child_dob", sa.Date(), nullable=False),
        sa.Column("nhs_number", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("initial_family_model")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "initial_family_model",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "family_name",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("child_dob", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "nhs_number",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="initial_family_model_pkey"),
    )
    op.drop_table("initial_families")
    # ### end Alembic commands ###
